# Copyright 2022 University of Illinois Urbana-Champaign. All rights reserved.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

In [2]:
warnings.filterwarnings(action = 'ignore')

In [3]:
df = pd.read_csv('weather_data_full.csv')

In [4]:
df

,Unnamed: 0,station_num,temp_ft,dewpt_ft,slp_mb,visib_mi,wind_knt,maxwind_knt,max_gust_knt,year,...,precip_in,precip_flag,max_temp_frnht,min_temp_frnht,ctry,st,lat,lon,elev(m),country name
0,0,718780,17.2,14.4,1007.6,10.2,6.8,12.0,0.0,2000,...,0.00,G,25.7,6.8,CA,NaN,52.183,-113.900,904.6,CANADA
1,1,718780,0.3,-6.7,1020.1,10.3,8.5,12.0,0.0,2000,...,0.05,G,6.6,-4.2,CA,NaN,52.183,-113.900,904.6,CANADA
2,2,718780,-6.6,-13.9,1028.0,15.0,4.9,8.0,0.0,2000,...,0.06,G,6.8,-13.0,CA,NaN,52.183,-113.900,904.6,CANADA
3,3,718780,12.6,6.3,1010.3,15.0,3.1,8.9,0.0,2000,...,0.00,G,26.8,3.2,CA,NaN,52.183,-113.900,904.6,CANADA
4,4,718780,20.3,16.8,1012.0,13.3,5.8,13.0,0.0,2000,...,0.00,H,28.2,5.2,CA,NaN,52.183,-113.900,904.6,CANADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48271718,2540612,165970,63.8,56.8,NaN,5.9,11.8,23.9,35.0,2000,...,0.00,NaN,0.0,57.2,MT,NaN,35.857,14.478,91.4,MALTA
48271719,2540613,165970,57.0,0.0,NaN,6.8,0.0,15.9,41.0,2000,...,0.20,F,61.9,52.0,MT,NaN,35.857,14.478,91.4,MALTA
48271720,2540614,165970,57.6,47.7,NaN,7.1,14.6,28.9,0.0,2000,...,0.05,F,62.4,53.6,MT,NaN,35.857,14.478,91.4,MALTA
48271721,2540615,165970,58.5,46.2,NaN,6.9,16.2,33.0,52.1,2000,...,0.03,F,61.7,57.2,MT,NaN,35.857,14.478,91.4,MALTA
48271722,2540616,165970,54.5,47.6,NaN,5.8,18.3,31.9,0.0,2000,...,0.28,F,57.2,51.8,MT,NaN,35.857,14.478,91.4,MALTA

In [5]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [6]:
df.shape

(48271723, 27)

In [7]:
df.columns

Index(['station_num', 'temp_ft', 'dewpt_ft', 'slp_mb', 'visib_mi', 'wind_knt',
       'maxwind_knt', 'max_gust_knt', 'year', 'month', 'day', 'fog', 'rain',
       'snow', 'hail', 'thunder', 'tornado', 'precip_in', 'precip_flag',
       'max_temp_frnht', 'min_temp_frnht', 'ctry', 'st', 'lat', 'lon',
       'elev(m)', 'country name'],
      dtype='object')

In [8]:
df.isna().sum()

station_num              0
temp_ft                171
dewpt_ft           1198026
slp_mb            11987708
visib_mi           5277117
wind_knt            289522
maxwind_knt         305387
max_gust_knt      15769050
year                     0
month                    0
day                      0
fog                      0
rain                     0
snow                     0
hail                     0
thunder                  0
tornado                  0
precip_in                0
precip_flag        3920327
max_temp_frnht           0
min_temp_frnht           0
ctry                     0
st                32417401
lat                  14896
lon                  14896
elev(m)              31407
country name             0
dtype: int64

In [9]:
df.to_csv('weather_data_full.csv', index = False)

In [10]:
df.isna().sum().sum() / df.size

0.05464890061190881